AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
